service: 
    name: shared-print-python-example
package:
  exclude:
    - venv/**
    - node_modules/**
    - tests/**    
custom:
  bucket: test-bucket-for-sp-csvs    
provider:
 name: aws
 runtime: python3.6
 memorySize: 128
 timeout: 10
 stage: production
 region: us-east-1
 iamRoleStatements:
    - Effect: Allow
      Action:
       - s3:GetObject
      Resource: arn:aws:s3:::${self:custom.bucket}/*            

functions:
    checkHoldingsByOCLCNumber: 
        handler: handler.checkHoldingsByOCLCNumber
        events:
         - s3:
            bucket: ${self:custom.bucket}
            event: s3:ObjectCreated:*
            rules:
              - prefix: holdingsByOCLCNumber
              - suffix: .csv         
    checkSPByOCLCNumber: 
        handler: handler.checkSPByOCLCNumber
        events:
         - s3:
            bucket: ${self:custom.bucket}
            event: s3:ObjectCreated:*
            rules:
              - prefix: retainedholdingsByOCLCNumber
              - suffix: .csv         
      